site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad bonus: individual/actividad_01.md
        - Actividad 1: individual/actividad_011.md
    - Colaborativas:
        - Actividad 1: todo.md
copyright: Â©GMDXX
site_author: GMDXX
